# This is a basic workflow to help you get started with Actions

name: Auto Health Report

# Controls when the workflow will run
on:
  push:
  schedule:
  # 定时任务，在每天的7点(beijin time)触发
    - cron: '0 23 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.0
        with:
          java-version: 13.0
      - name: start task
        run: java -jar SeleniumTest.jar
      
